package static_data

type Gear struct {
	Name       string
	Category   string // general, Alchemical Concoctions, Ammunition, etc
	CostAmount int
	CostCoin   string  // gp, sp, cp
	WeightEach float64 // in pounds.  So, .5, 1, 25.75, etc
	Quantity   int
}

var AdventuringGear = map[string]map[string]Gear{
	"general": {
		"abacus": {
			Name:       "Abacus",
			Category:   "General", // General, Alchemical Concoctions, Ammunition, etc
			CostAmount: 2,
			CostCoin:   "gp", // gp, sp, cp
			WeightEach: 2,
			Quantity:   1,
		},
		"ball bearings": {
			Name:       "Ball Bearings (bag)",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 2,
			Quantity:   1000,
		},
		"bedroll": {
			Name:       "Bedroll",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 7,
			Quantity:   1,
		},
		"bell": {
			Name:       "Bell",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 0,
			Quantity:   1,
		},
		"blanket": {
			Name:       "Blanket",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "sp",
			WeightEach: 3,
			Quantity:   1,
		},
		"block and tackle": {
			Name:       "Block and Tackle",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 5,
			Quantity:   1,
		},
		"book": {
			Name:       "Book",
			Category:   "General",
			CostAmount: 25,
			CostCoin:   "gp",
			WeightEach: 5,
			Quantity:   1,
		},
		"caltrops": {
			Name:       "Caltrops (bag)",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 2,
			Quantity:   20,
		},
		"candle": {
			Name:       "Candle",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "cp",
			WeightEach: 0,
			Quantity:   1,
		},
		"case": {
			Name:       "Case, map or scroll",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 1,
			Quantity:   1,
		},
		"chain": {
			Name:       "Chain (10 feet)",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 10,
			Quantity:   1,
		},
		"chalk": {
			Name:       "Chalk",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "cp",
			WeightEach: 0,
			Quantity:   1,
		},
		"climber's kit": {
			Name:       "Climber's Kit",
			Category:   "General",
			CostAmount: 25,
			CostCoin:   "gp",
			WeightEach: 12,
			Quantity:   1,
		},
		"clothes common": {
			Name:       "Clothes, common",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "sp",
			WeightEach: 3,
			Quantity:   1,
		},
		"clothes costume": {
			Name:       "Clothes, costume",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 4,
			Quantity:   1,
		},
		"clothes fine": {
			Name:       "Clothes, fine",
			Category:   "General",
			CostAmount: 15,
			CostCoin:   "gp",
			WeightEach: 6,
			Quantity:   1,
		},
		"component pouch": {
			Name:       "Component Pouch",
			Category:   "General",
			CostAmount: 25,
			CostCoin:   "gp",
			WeightEach: 2,
			Quantity:   1,
		},
		"crowbar": {
			Name:       "Crowbar",
			Category:   "General",
			CostAmount: 2,
			CostCoin:   "gp",
			WeightEach: 5,
			Quantity:   1,
		},
		"fishing tackle": {
			Name:       "Fishing Tackle",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 4,
			Quantity:   1,
		},
		"hammer": {
			Name:       "Hammer",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 3,
			Quantity:   1,
		},
		"healer's kit": {
			Name:       "Healer's Kit",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 3,
			Quantity:   1,
		},
		"holy water": {
			Name:       "Holy Water (flask)",
			Category:   "General",
			CostAmount: 25,
			CostCoin:   "gp",
			WeightEach: 1,
			Quantity:   1,
		},
		"hourglass": {
			Name:       "Hourglass",
			Category:   "General",
			CostAmount: 25,
			CostCoin:   "gp",
			WeightEach: 1,
			Quantity:   1,
		},
		"hunting trap": {
			Name:       "Hunting Trap, basic",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 25,
			Quantity:   1,
		},
		"ink": {
			Name:       "Ink (1-ounce bottle)",
			Category:   "General",
			CostAmount: 10,
			CostCoin:   "gp",
			WeightEach: 0,
			Quantity:   1,
		},
		"ink pen": {
			Name:       "Ink Pen",
			Category:   "General",
			CostAmount: 2,
			CostCoin:   "cp",
			WeightEach: 0,
			Quantity:   1,
		},
		"ladder": {
			Name:       "Ladder (10-foot)",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "sp",
			WeightEach: 25,
			Quantity:   1,
		},
		"lamp": {
			Name:       "Lamp",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "sp",
			WeightEach: 1,
			Quantity:   1,
		},
		"lantern bullseye": {
			Name:       "Lantern, bullseye",
			Category:   "General",
			CostAmount: 10,
			CostCoin:   "gp",
			WeightEach: 2,
			Quantity:   1,
		},
		"lantern hooded": {
			Name:       "Lantern, hooded",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 2,
			Quantity:   1,
		},
		"lock": {
			Name:       "Lock",
			Category:   "General",
			CostAmount: 10,
			CostCoin:   "gp",
			WeightEach: 1,
			Quantity:   1,
		},
		"magnifying glass": {
			Name:       "Magnifying Glass",
			Category:   "General",
			CostAmount: 100,
			CostCoin:   "gp",
			WeightEach: 0,
			Quantity:   1,
		},
		"manacles": {
			Name:       "Manacles",
			Category:   "General",
			CostAmount: 2,
			CostCoin:   "gp",
			WeightEach: 6,
			Quantity:   1,
		},
		"mess kit": {
			Name:       "Mess Kit",
			Category:   "General",
			CostAmount: 2,
			CostCoin:   "sp",
			WeightEach: 1,
			Quantity:   1,
		},
		"mirror": {
			Name:       "Mirror, compact",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 0.5,
			Quantity:   1,
		},
		"net": {
			Name:       "Net",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 3,
			Quantity:   1,
		},
		"paper": {
			Name:       "Paper (one sheet)",
			Category:   "General",
			CostAmount: 2,
			CostCoin:   "sp",
			WeightEach: 0,
			Quantity:   1,
		},
		"miner's pick": {
			Name:       "Pick, miner's",
			Category:   "General",
			CostAmount: 2,
			CostCoin:   "gp",
			WeightEach: 10,
			Quantity:   1,
		},
		"piton": {
			Name:       "Piton",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "cp",
			WeightEach: 0.25,
			Quantity:   1,
		},
		"pole": {
			Name:       "Pole (10-foot)",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "cp",
			WeightEach: 7,
			Quantity:   1,
		},
		"potion of healing": {
			Name:       "Potion of Healing",
			Category:   "General",
			CostAmount: 50,
			CostCoin:   "gp",
			WeightEach: 0.5,
			Quantity:   1,
		},
		"quiver": {
			Name:       "Quiver",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 1,
			Quantity:   1,
		},
		"portable ram": {
			Name:       "Ram, portable",
			Category:   "General",
			CostAmount: 4,
			CostCoin:   "gp",
			WeightEach: 35,
			Quantity:   1,
		},
		"rations": {
			Name:       "Rations (1 day)",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "sp",
			WeightEach: 2,
			Quantity:   1,
		},
		"rope": {
			Name:       "Rope (50 feet)",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 10,
			Quantity:   1,
		},
		"sealing wax": {
			Name:       "Sealing Wax",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "sp",
			WeightEach: 0,
			Quantity:   1,
		},
		"merchant's scale": {
			Name:       "Scale, merchant's",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 3,
			Quantity:   1,
		},
		"shovel": {
			Name:       "Shovel",
			Category:   "General",
			CostAmount: 2,
			CostCoin:   "gp",
			WeightEach: 5,
			Quantity:   1,
		},
		"signal whistle": {
			Name:       "Signal Whistle",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "cp",
			WeightEach: 0,
			Quantity:   1,
		},
		"signet ring": {
			Name:       "Signet Ring",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 0,
			Quantity:   1,
		},
		"soap": {
			Name:       "Soap",
			Category:   "General",
			CostAmount: 2,
			CostCoin:   "cp",
			WeightEach: 0,
			Quantity:   1,
		},
		"spellbook": {
			Name:       "Spellbook",
			Category:   "General",
			CostAmount: 50,
			CostCoin:   "gp",
			WeightEach: 3,
			Quantity:   1,
		},
		"iron spikes": {
			Name:       "Spikes, iron",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 0.5,
			Quantity:   10,
		},
		"spyglass": {
			Name:       "Spyglass",
			Category:   "General",
			CostAmount: 1000,
			CostCoin:   "gp",
			WeightEach: 1,
			Quantity:   1,
		},
		"tent": {
			Name:       "Tent, two-person",
			Category:   "General",
			CostAmount: 2,
			CostCoin:   "gp",
			WeightEach: 20,
			Quantity:   1,
		},
		"tinderbox": {
			Name:       "Tinderbox",
			Category:   "General",
			CostAmount: 5,
			CostCoin:   "sp",
			WeightEach: 1,
			Quantity:   1,
		},
		"torch": {
			Name:       "Torch",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "cp",
			WeightEach: 1,
			Quantity:   1,
		},
		"whetstone": {
			Name:       "Whetstone",
			Category:   "General",
			CostAmount: 1,
			CostCoin:   "cp",
			WeightEach: 1,
			Quantity:   1,
		},
	},

	"alchemical concoctions": {
		"acid (vial)": {
			Name:       "Acid (vial)",
			Category:   "Alchemical Concoctions", // General, Alchemical Concoctions, Ammunition, etc
			CostAmount: 25,
			CostCoin:   "gp", // gp, sp, cp
			WeightEach: 1,
			Quantity:   1,
		},
		"alchemist's fire": {
			Name:       "Alchemist's fire (flask)",
			Category:   "Alchemical Concoctions",
			CostAmount: 50,
			CostCoin:   "gp",
			WeightEach: 1,
			Quantity:   1,
		},
		"oil": {
			Name:       "Oil (flask)",
			Category:   "Alchemical Concoctions",
			CostAmount: 1,
			CostCoin:   "sp",
			WeightEach: 1,
			Quantity:   1,
		},
	},
	"ammunition": {
		"arrows": {
			Name:       "Arrows (20)",
			Category:   "Ammunition", // General, Alchemical Concoctions, Ammunition, etc
			CostAmount: 1,
			CostCoin:   "gp", // gp, sp, cp
			WeightEach: 1,
			Quantity:   20,
		},
		"blowgun needles": {
			Name:       "Blowgun needles (50)",
			Category:   "Ammunition",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 1,
			Quantity:   50,
		},
		"crossbow bolts": {
			Name:       "Crossbow bolts (20)",
			Category:   "Ammunition",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 1.5,
			Quantity:   20,
		},
		"sling bullets": {
			Name:       "Sling bullets (20)",
			Category:   "Ammunition",
			CostAmount: 4,
			CostCoin:   "cp",
			WeightEach: 1.5,
			Quantity:   20,
		},
	},
	"containers": {
		"backpack": {
			Name:       "Backpack",
			Category:   "Containers",
			CostAmount: 2,
			CostCoin:   "gp",
			WeightEach: 5,
			Quantity:   1,
		},
		"barrel": {
			Name:       "Barrel",
			Category:   "Containers",
			CostAmount: 2,
			CostCoin:   "gp",
			WeightEach: 70,
			Quantity:   1,
		},
		"basket": {
			Name:       "Basket",
			Category:   "Containers",
			CostAmount: 4,
			CostCoin:   "sp",
			WeightEach: 2,
			Quantity:   1,
		},
		"bottle": {
			Name:       "Bottle, glass",
			Category:   "Containers",
			CostAmount: 2,
			CostCoin:   "gp",
			WeightEach: 2,
			Quantity:   1,
		},
		"chest": {
			Name:       "Chest",
			Category:   "Containers",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 25,
			Quantity:   1,
		},
		"flask": {
			Name:       "Flask or tankard",
			Category:   "Containers",
			CostAmount: 2,
			CostCoin:   "cp",
			WeightEach: 1,
			Quantity:   1,
		},
		"jug": {
			Name:       "Jug or pitcher",
			Category:   "Containers",
			CostAmount: 2,
			CostCoin:   "cp",
			WeightEach: 4,
			Quantity:   1,
		},
		"cooking pot": {
			Name:       "Pot, cooking",
			Category:   "Containers",
			CostAmount: 2,
			CostCoin:   "gp",
			WeightEach: 10,
			Quantity:   1,
		},
		"pouch": {
			Name:       "Pouch",
			Category:   "Containers",
			CostAmount: 5,
			CostCoin:   "sp",
			WeightEach: 1,
			Quantity:   1,
		},
		"sack": {
			Name:       "Sack",
			Category:   "Containers",
			CostAmount: 1,
			CostCoin:   "cp",
			WeightEach: 0.5,
			Quantity:   1,
		},
		"vial": {
			Name:       "Vial",
			Category:   "Containers",
			CostAmount: 1,
			CostCoin:   "gp",
			WeightEach: 0,
			Quantity:   1,
		},
		"waterskin": {
			Name:       "Waterskin (full)",
			Category:   "Containers",
			CostAmount: 2,
			CostCoin:   "sp",
			WeightEach: 5,
			Quantity:   1,
		},
	},
	"herbal concoctions": {
		"antitoxin": {
			Name:       "Antitoxin (vial)",
			Category:   "Herbal Concoctions",
			CostAmount: 50,
			CostCoin:   "gp", // gp, sp, cp
			WeightEach: 0,
			Quantity:   1,
		},
		"perfume": {
			Name:       "Perfume (vial)",
			Category:   "Herbal Concoctions",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 0,
			Quantity:   1,
		},
		"poison basic": {
			Name:       "Poison, basic (vial)",
			Category:   "Herbal Concoctions",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 0,
			Quantity:   1,
		},
		"poison ether": {
			Name:       "Poison, essence of ether (vial)",
			Category:   "Herbal Concoctions",
			CostAmount: 300,
			CostCoin:   "gp",
			WeightEach: 0,
			Quantity:   1,
		},
		"poison last gasp": {
			Name:       "Poison, last gasp (vial)",
			Category:   "Herbal Concoctions",
			CostAmount: 200,
			CostCoin:   "gp",
			WeightEach: 0,
			Quantity:   1,
		},
		"poison midnight tears": {
			Name:       "Poison, midnight tears (vial)",
			Category:   "Herbal Concoctions",
			CostAmount: 1500,
			CostCoin:   "gp",
			WeightEach: 0,
			Quantity:   1,
		},
	},
	"spellcasting foci": {
		"arcane focus": {
			Name:       "Arcane Focus",
			Category:   "Spellcasting Foci",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 2,
			Quantity:   1,
		},
		"holy symbol": {
			Name:       "Holy Symbol",
			Category:   "Spellcasting Foci",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 2,
			Quantity:   1,
		},
		"primordial focus": {
			Name:       "Primordial Focus",
			Category:   "Spellcasting Foci",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 2,
			Quantity:   1,
		},
		"wyrd focus": {
			Name:       "Wyrd Focus",
			Category:   "Spellcasting Foci",
			CostAmount: 5,
			CostCoin:   "gp",
			WeightEach: 2,
			Quantity:   1,
		},
	},
}
