
services:
  tov-pgs:
    build: ./pgs
    image: mdbdba/tov-postgres:17.5
    container_name: tov-pgs
    ports:
      - "5777:5432"
    networks:
      - rpg
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD_FILE=/db_pass
     - POSTGRES_DB=rpg
    volumes:
     - ~/docker_data/pgs/tov/data:/var/lib/postgresql/data
  # tov-tools:
  #   env_file:
  #     - .env.local
  #   environment:
  #     - DB_HOST=${POSTGRES_HOST}
  #     - DB_PORT=${POSTGRES_PORT}
  #     - DB_USER=${POSTGRES_USER}
  #     - DB_PASSWORD=${POSTGRES_PASSWORD}
  #     - DB_NAME=${POSTGRES_DB}
  #     - DB_SSL_MODE=${DB_SSL_MODE}
  #   networks:
  #     - rpg
  #   depends_on:
  #     - tov-pgs

networks:
  rpg:
    driver: bridge
